---
# Example inventory for Kubernetes cluster testing
# Modify this file according to your actual cluster setup

all:
  children:
    k8s_cluster:
      children:
        control_plane:
          hosts:
            master1:
              ansible_host: 192.168.1.10
              ansible_user: ubuntu

        workers:
          hosts:
            worker1:
              ansible_host: 192.168.1.11
              ansible_user: ubuntu
            worker2:
              ansible_host: 192.168.1.12
              ansible_user: ubuntu

      vars:
        ansible_python_interpreter: /usr/bin/python3
        k8s_version: "1.28"
        kubectl_version: "1.28.0"

    localhost:
      hosts:
        local:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
